package project_package;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Richard Ngabo
 */
public class adminPage extends javax.swing.JFrame {

    public adminPage() {
        initComponents();
        populateAdminViewTable();
    }

    // Method to populate adminViewTable with data from the database
    private void populateAdminViewTable() {
        try {
            // Establish connection to the database
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/employees", "root", "");

            // Prepare SQL query to retrieve data from employee_details table
            String query = "SELECT * FROM employee_details";
            Statement statement = connection.prepareStatement(query);

            // Execute the query
            ResultSet resultSet = statement.executeQuery(query);

            // Create a DefaultTableModel to hold the data for JTable
            DefaultTableModel model = (DefaultTableModel) adminViewTable.getModel();

            // Clear existing rows from the table
            model.setRowCount(0);

            // Get metadata about the ResultSet (number of columns)
            ResultSetMetaData metaData = resultSet.getMetaData();
            int columnCount = metaData.getColumnCount();

            // Create an array to hold column names
            String[] columnNames = new String[columnCount];
            for (int i = 0; i < columnCount; i++) {
                // Get the column name from metadata
                columnNames[i] = metaData.getColumnName(i + 1); // Columns are 1-indexed
            }

            // Set column names of the table model
            model.setColumnIdentifiers(columnNames);

            // Iterate through the result set and add rows to the table model
            while (resultSet.next()) {
                Object[] row = new Object[columnCount];
                for (int i = 0; i < columnCount; i++) {
                    row[i] = resultSet.getObject(i + 1); // Columns are 1-indexed
                }
                model.addRow(row);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        } finally {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeTitle = new javax.swing.JLabel();
        adminName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminViewTable = new javax.swing.JTable();
        logoutAdmin = new javax.swing.JButton();
        detailsPage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        employeeTitle.setText("Employees");
        getContentPane().add(employeeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        adminName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        adminName.setText("Admin");
        getContentPane().add(adminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 15, -1, -1));

        adminViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(adminViewTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 65, 651, -1));

        logoutAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutAdmin.setText("Logout");
        getContentPane().add(logoutAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 543, 125, 47));

        detailsPage.setBackground(new java.awt.Color(0, 0, 204));
        detailsPage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        detailsPage.setForeground(new java.awt.Color(255, 255, 255));
        detailsPage.setText("Details Page");
        getContentPane().add(detailsPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 543, 131, 47));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminName;
    private javax.swing.JTable adminViewTable;
    private javax.swing.JButton detailsPage;
    private javax.swing.JLabel employeeTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutAdmin;
    // End of variables declaration//GEN-END:variables
}
